### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by rodolfohernandez** [rodolfohernandez/RH-Writing-Website#2]
Need to agree on a Favicon to use. I still have the old one, but it's far from optimal. I figured we'd probably want to change it with an upgraded file.
![favicon](https://cloud.githubusercontent.com/assets/19175515/16246109/cf0f7cae-37d1-11e6-88c4-6aa8643bc01a.JPG)

Common size looks like 16 x 16, preferably in an .SVG format. Transparent background might be a good look, guess it depends on the platform. Should we just use the new icon from the  header in the wireframes? Or something else entirely?

**Comment by blaynecameron** [comment]
Yeah we can address that last when the site is almost done. It will just be "RH" in the current font we see in the logo (Playfair).

**Comment by rodolfohernandez** [comment]
Ok cool
